version: 2
workflows:
  test:
    jobs:
{%- if cookiecutter.minimum_python_version|float <= 3.6 %}
      - test-3.6
{%- endif %}
{%- if cookiecutter.minimum_python_version|float <= 3.7 %}
      - test-3.7
{%- endif %}
{%- if cookiecutter.support_python2 != "n" %}
      - test-2.7
{%- endif %}
references:
  test-common: &test-common
    working_directory: ~/repo
  steps:
    restore-cache: &restore-cache
      restore_cache:
        keys:
          - c-pip-cache
    prepare-venv: &prepare-venv
      run:
        name: Prepare venv and dependencies
        command: |
          python -m venv venv || virtualenv venv
          . venv/bin/activate
          pip install --cache-dir ~/pip-cache -e .[dev]
    save-cache: &save-cache
      save_cache:
        paths:
          - ~/pip-cache
        key: c-pip-cache
jobs:
{%- if cookiecutter.minimum_python_version|float <= 3.6 %}
  test-3.6:
    <<: *test-common
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      - checkout
      - *restore-cache
      - *prepare-venv
      - *save-cache
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            tox -e py36
{%- endif %}
{%- if cookiecutter.minimum_python_version|float <= 3.7 %}
  test-3.7:
    <<: *test-common
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - checkout
      - *restore-cache
      - *prepare-venv
      - *save-cache
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            tox -e py37
{%- endif %}
{%- if cookiecutter.support_python2 != "n" %}
  test-2.7:
    <<: *test-common
    docker:
      - image: circleci/python:2.7-stretch
    steps:
      - checkout
      - *restore-cache
      - *prepare-venv
      - *save-cache
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            tox -e py27
{%- endif %}
